/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rafael Fernández Calvo (https://sketchfab.com/rafarelo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rockola-positiva-1114cbce83ff460bad46b8910548d9db
Title: Rockola positiva
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    MaquinaMusica_low_PBR_0: THREE.Mesh;
    ["Rejilla-Frontal_low_PBR_0"]: THREE.Mesh;
    Rueda_low_PBR_0: THREE.Mesh;
    Rueda_Soporte_low_PBR_0: THREE.Mesh;
    Rueda_low001_PBR_0: THREE.Mesh;
    Rueda_Soporte_low001_PBR_0: THREE.Mesh;
    Rueda_low002_PBR_0: THREE.Mesh;
    Rueda_Soporte_low002_PBR_0: THREE.Mesh;
    Rueda_low003_PBR_0: THREE.Mesh;
    Rueda_Soporte_low003_PBR_0: THREE.Mesh;
    Rueda_Soporte_low004_PBR_0: THREE.Mesh;
    Rueda_Soporte_low005_PBR_0: THREE.Mesh;
    PuertaDelantera_Movil_low_PBR_0: THREE.Mesh;
    Canciones_Organizador_low_PBR_0: THREE.Mesh;
    Triangulos_low_PBR_0: THREE.Mesh;
    Estrella_01_low_PBR_0: THREE.Mesh;
    Logotipo_low_PBR_0: THREE.Mesh;
    Estrella_01_low001_PBR_0: THREE.Mesh;
    PuertaDelantera_Movil_Cristal_PBR_0: THREE.Mesh;
    Mecanismo_Estructura001_low_PBR_0: THREE.Mesh;
    ["C��rculo012_PBR_0"]: THREE.Mesh;
    ["C��rculo013_PBR_0"]: THREE.Mesh;
    Estructura_004004_PBR_0: THREE.Mesh;
    Estructura_004005_PBR_0: THREE.Mesh;
    ["C��rculo026_PBR_0"]: THREE.Mesh;
    Plano001_PBR_0: THREE.Mesh;
    ["C��rculo027_PBR_0"]: THREE.Mesh;
    Plano011_PBR_0: THREE.Mesh;
    Plano012_PBR_0: THREE.Mesh;
    Estructura_004006_PBR_0: THREE.Mesh;
    ["C��rculo030_PBR_0"]: THREE.Mesh;
    Plano013_PBR_0: THREE.Mesh;
    Plano016_PBR_0: THREE.Mesh;
    ["C��rculo033_PBR_0"]: THREE.Mesh;
    Estructura_004008_PBR_0: THREE.Mesh;
    Plano_PBR_0: THREE.Mesh;
    Plano019_PBR_0: THREE.Mesh;
    ["C��rculo001_PBR_0"]: THREE.Mesh;
    ["Selector-Canciones-Rueda_low_PBR_0"]: THREE.Mesh;
    ["C��rculo006_PBR_0"]: THREE.Mesh;
    ["C��rculo004_PBR_0"]: THREE.Mesh;
    Estructura_004001_PBR_0: THREE.Mesh;
    Plano015_PBR_0: THREE.Mesh;
    Estructura_004009_PBR_0: THREE.Mesh;
    ["C��rculo034_PBR_0"]: THREE.Mesh;
    Plano017_PBR_0: THREE.Mesh;
    Plano018_PBR_0: THREE.Mesh;
    Vinillo02_low_PBR_0: THREE.Mesh;
    ["C��rculo031_PBR_0"]: THREE.Mesh;
    Gear003_PBR_0: THREE.Mesh;
    Gear004_PBR_0: THREE.Mesh;
    Plano014_PBR_0: THREE.Mesh;
    ["C��rculo002_PBR_0"]: THREE.Mesh;
    Gear005_PBR_0: THREE.Mesh;
    ["C��rculo035_PBR_0"]: THREE.Mesh;
    ["C��rculo037_PBR_0"]: THREE.Mesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    material: THREE.MeshPhysicalMaterial;
    glass: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Esqueleto|Thank You Gratitude Affirmations";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Jukebox(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "models/misc/jukebox.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<THREE.AnimationClip>(animations, group);

  useEffect(() => {
    if(materials.material){
        actions["Esqueleto|Thank You Gratitude Affirmations"]?.play();
        console.log(materials)

    }
  
  }, [materials.material]);
 

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.011}
        >
          <group
            name="3a0c3a52026c4e73a9034d32cf58c8ddfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="MaquinaMusica_low"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="MaquinaMusica_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.MaquinaMusica_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rejilla-Frontal_low"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Rejilla-Frontal_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Rejilla-Frontal_low_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_low"
                  position={[33.709, 0.001, 26.906]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_Soporte_low"
                  position={[33.709, 0.001, 26.906]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_Soporte_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_Soporte_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_low001"
                  position={[-34.284, 0.001, 26.17]}
                  rotation={[-Math.PI / 2, 0, 2.171]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_low001_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_low001_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_Soporte_low001"
                  position={[-34.284, 0.001, 26.17]}
                  rotation={[-Math.PI / 2, 0, -1.816]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_Soporte_low001_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_Soporte_low001_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_low002"
                  position={[-32.893, 0.001, -27.898]}
                  rotation={[-Math.PI / 2, 0, 3.112]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_low002_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_low002_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_Soporte_low002"
                  position={[-32.893, 0.001, -27.898]}
                  rotation={[-Math.PI / 2, 0, 3.112]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_Soporte_low002_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_Soporte_low002_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_low003"
                  position={[32.786, 0.001, -28.024]}
                  rotation={[-Math.PI / 2, 0, 0.128]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_low003_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_low003_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_Soporte_low003"
                  position={[32.786, 0.001, -28.024]}
                  rotation={[-Math.PI / 2, 0, 1.381]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_Soporte_low003_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_Soporte_low003_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_Soporte_low004"
                  position={[-34.284, 0.001, 26.17]}
                  rotation={[-Math.PI / 2, 0, 2.171]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_Soporte_low004_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_Soporte_low004_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Rueda_Soporte_low005"
                  position={[32.786, 0.001, -28.024]}
                  rotation={[-Math.PI / 2, 0, 0.128]}
                  scale={100}
                >
                  <mesh
                    name="Rueda_Soporte_low005_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Rueda_Soporte_low005_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="PuertaDelantera_Movil_low"
                  position={[0, 83.502, 29.884]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="PuertaDelantera_Movil_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.PuertaDelantera_Movil_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Canciones_Organizador_low"
                  position={[34.432, 109.508, -12.651]}
                  rotation={[-2.014, 0, -0.469]}
                  scale={100}
                >
                  <mesh
                    name="Canciones_Organizador_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Canciones_Organizador_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Triangulos_low"
                  position={[27.434, 70.101, 32.925]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={110.859}
                >
                  <mesh
                    name="Triangulos_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Triangulos_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Estrella_01_low"
                  position={[34.11, 67.703, 33.188]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={233.451}
                >
                  <mesh
                    name="Estrella_01_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Estrella_01_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Logotipo_low"
                  position={[-30.396, 38.391, 31.006]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Logotipo_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Logotipo_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Estrella_01_low001"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Estrella_01_low001_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Estrella_01_low001_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="PuertaDelantera_Movil_Cristal"
                  position={[0, 83.502, 29.884]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="PuertaDelantera_Movil_Cristal_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.PuertaDelantera_Movil_Cristal_PBR_0.geometry
                    }
                    material={materials.glass}
                  />
                </group>
                <group
                  name="Mecanismo_Estructura001_low"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Mecanismo_Estructura001_low_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mecanismo_Estructura001_low_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo012"
                  position={[21.925, 92.801, 18.894]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo012_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo012_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo013"
                  position={[21.925, 92.609, 18.99]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo013_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo013_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Estructura_004004"
                  position={[0, 0.082, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Estructura_004004_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Estructura_004004_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Estructura_004005"
                  position={[0, 0.082, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Estructura_004005_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Estructura_004005_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo026"
                  position={[21.925, 92.801, 18.894]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo026_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo026_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano001"
                  position={[0, 78.024, 19.38]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano001_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano001_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo027"
                  position={[0, 78.024, 26.6]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo027_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo027_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano011"
                  position={[3.545, 78.759, 23.563]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano011_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano011_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano012"
                  position={[3.545, 73.878, 23.563]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano012_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano012_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Estructura_004006"
                  position={[0, 0.082, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Estructura_004006_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Estructura_004006_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo030"
                  position={[0, 96.686, -6.062]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo030_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo030_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano013"
                  position={[-0.006, 86.834, -23.542]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano013_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano013_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano016"
                  position={[-21.573, 92.683, 19.107]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano016_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano016_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo033"
                  position={[-0.067, 96.686, -6.062]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo033_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo033_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Estructura_004008"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Estructura_004008_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Estructura_004008_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano"
                  position={[-21.829, 91.972, 18.731]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Plano019"
                  position={[0, 78.024, 19.38]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Plano019_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plano019_PBR_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="C��rculo001"
                  position={[0, 96.686, -6.062]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="C��rculo001_PBR_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["C��rculo001_PBR_0"].geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name="Esqueleto"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_81">
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/misc/jukebox.glb");
